SELECT*FROM Itinerario
SELECT*FROM Conductor
SELECT*FROM Vehiculo

INSERT INTO Vehiculo VALUES('DSA-896','TUCSON',4,1,'HUNDAY')
INSERT INTO Conductor VALUES(1,'CARLOS','LOPEZ CERRON','896576',1)
INSERT INTO Itinerario VALUES (1,'LIMA-ICA','LIMA','ICA',250,1)